# Ensemble model configuration
models_to_ensemble: ["dynunet", "unet", "basicunet"]  # Model types to include in ensemble
in_channels: 1
out_channels: 2  # Background + Foreground (colon cancer)
dimensions: 3  # 3D segmentation

# Model weights (importance in ensemble)
model_weights:
  dynunet: 0.5    # Higher weight for DynUNet (usually best performer)
  unet: 0.3
  basicunet: 0.2

# Model directory containing checkpoints
model_dir: "./outputs/models"  # Update with your models directory

# Data configuration
data_dir: "/path/to/Task10_Colon"  # Update this path to your dataset location
intensity_bounds: [-175, 250]  # HU range for CT images

# Inference settings
roi_size: [96, 96, 96]  # Size of sliding window patches
sw_batch_size: 4  # Batch size for sliding window inference
overlap: 0.5  # Overlap between sliding windows
num_workers: 4  # Number of worker processes for data loading

# Test-time augmentation
use_tta: true  # Whether to use test-time augmentation

# Post-processing
apply_post_processing: true
min_tumor_size_mm3: 50  # Remove small isolated predictions (50 mm³)

# Visualization settings
num_visualizations: 10  # Number of cases to visualize

# Output directory
output_dir: "./results/ensemble"

# Device settings
device: "cuda"  # Options: cuda, cuda:0, cpu
